"use client";

import { cn } from "@/lib/utils";
import { modelLabel } from "@/lib/modelLabels";

export function ModelPill({
  slug,
  className,
  pending = false,
}: {
  slug?: string | null;
  className?: string;
  /** Expected model before the stream confirms via header / onFinish. */
  pending?: boolean;
}) {
  if (!slug) return null;
  const { short, tone } = modelLabel(slug);
  const dataAction = tone === "amber" ? "assumptions" : tone === "violet" ? "derive" : "explain";

  return (
    <span
      data-action={dataAction}
      className={cn(
        "inline-flex items-center gap-1 rounded-full border border-border/55 bg-muted/30 px-1.5 py-px text-[10px] font-medium tracking-[0.04em] text-foreground/80",
        pending && "text-foreground/70 motion-safe:animate-pulse",
        className,
      )}
      style={pending ? { opacity: 0.75 } : undefined}
      title={pending ? `Using ${slug} (confirming…)` : `Generated by ${slug}`}
    >
      <span
        aria-hidden
        className="h-1.5 w-1.5 rounded-full"
        style={{ background: "rgb(var(--highlight-rgb) / 0.85)" }}
      />
      {short}
    </span>
  );
}
