/**
 * Lite summary stream (PROMPT_7 Track D).
 *
 * Returns the high-signal first impression (overview + tl_dr + key
 * contributions + a few key equations) in ~10 s so the Summary panel
 * shows something useful immediately. The deep body is generated by
 * the existing `/summary-stream` route, kicked off only after the lite
 * phase lands.
 *
 * Persists to `cached_analysis.summary_lite` so a returning visit
 * renders instantly without spending tokens twice.
 */

import { NextResponse } from "next/server";
import { streamObject } from "ai";
import { zodSchema } from "@ai-sdk/provider-utils";

import { getModelFromSlug, maxOutputTokensFor } from "@/lib/server/llm";
import { promptDepthForModel } from "@/lib/modelLabels";
import { requireUser, AuthError } from "@/lib/server/auth";
import {
  fetchPaperContext,
  resolveStreamModelOverride,
  reserveUsage,
  releaseUsage,
  upsertCachedAnalysis,
  InternalApiError,
  type UsageToken,
} from "@/lib/server/internalApi";
import { fetchUserPrefs } from "@/lib/server/userPrefs";
import {
  PaperSummaryLiteSchema,
  type PaperSummaryLite,
} from "@/lib/server/schemas";
import { buildSummaryLitePrompt } from "@/lib/server/prompts/summary";
import { capPaperRawText } from "@/lib/server/paperTextCap";
import {
  cachedUserMessages,
  providerOptionsForSlug,
} from "@/lib/server/promptCache";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
/** Lite never exceeds 30 s in practice; cap at 60 s with Vercel headroom. */
export const maxDuration = 60;

const PAPER_ID_RE = /^[a-zA-Z0-9_-]+$/;

function jsonError(
  status: number,
  code: string,
  message: string,
  extra: Record<string, unknown> = {},
): Response {
  return NextResponse.json({ detail: { code, message, ...extra } }, { status });
}

export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> },
): Promise<Response> {
  const { id: paperId } = await params;
  if (!paperId || !PAPER_ID_RE.test(paperId)) {
    return jsonError(400, "bad_paper_id", "Invalid paper id");
  }

  let user: { userId: string; tier: string };
  try {
    user = await requireUser();
  } catch (e) {
    if (e instanceof AuthError) return jsonError(e.status, e.code, e.message);
    return jsonError(401, "unauthorized", "Unauthorized");
  }

  let body: Record<string, unknown> = {};
  try {
    body = (await request.json()) as Record<string, unknown>;
  } catch {
    body = {};
  }

  // Lite uses the *fast* model by default — Haiku is plenty for an
  // overview + 3 bullets and finishes in 5–8 s. The user's analysis
  // model is still honored when they overrode it explicitly.
  let paper: { title: string; raw_text: string };
  let liteModel: string;
  let deepAnalysis = false;
  try {
    const [ctx, prefs] = await Promise.all([
      fetchPaperContext(paperId, user.userId),
      fetchUserPrefs(user.userId),
    ]);
    paper = { title: ctx.title, raw_text: capPaperRawText(ctx.raw_text) };
    deepAnalysis = prefs.deep_analysis;
    liteModel = await resolveStreamModelOverride(
      user.userId,
      body,
      prefs.fast_model || prefs.analysis_model,
    );
  } catch (e) {
    if (e instanceof InternalApiError) {
      const status = e.status === 404 ? 404 : 502;
      const code = e.status === 404 ? "paper_not_found" : "internal_unavailable";
      return jsonError(status, code, e.message);
    }
    return jsonError(502, "paper_fetch_failed", "Could not load paper context");
  }

  let usageToken: UsageToken | null = null;
  try {
    const reserve = await reserveUsage({
      userId: user.userId,
      paperId,
      kind: "summary",
      model: liteModel,
    });
    usageToken = reserve.token;
  } catch (e) {
    if (e instanceof InternalApiError) {
      const detail = e.detail as { detail?: Record<string, unknown> } | undefined;
      const inner = (detail?.detail ?? {}) as Record<string, unknown>;
      const code = (inner.code as string) || (e.status === 403 ? "tier_locked" : "rate_limited");
      const message = (inner.message as string) || e.message;
      return jsonError(e.status, code, message, { ...inner });
    }
    return jsonError(503, "usage_unavailable", "Usage tracking unavailable");
  }

  const depth = promptDepthForModel(liteModel);
  const { system, paperContextText, taskText } = buildSummaryLitePrompt({
    paperTitle: paper.title,
    paperContext: paper.raw_text,
    depth,
    deepAnalysis,
  });

  let releasedOnError = false;
  const releaseOnFailure = async () => {
    if (releasedOnError) return;
    releasedOnError = true;
    if (usageToken) await releaseUsage(usageToken);
  };

  let result: ReturnType<typeof streamObject>;
  try {
    result = streamObject({
      model: getModelFromSlug(liteModel),
      schema: zodSchema(PaperSummaryLiteSchema),
      schemaName: "PaperSummaryLite",
      schemaDescription: "Fast first-impression summary of an academic paper.",
      system,
      messages: cachedUserMessages(liteModel, paperContextText, taskText),
      ...(providerOptionsForSlug(liteModel)
        ? { providerOptions: providerOptionsForSlug(liteModel) }
        : {}),
      temperature: 0.3,
      // ~2k tokens is plenty for overview + tl_dr + 5 bullets + 3 eqs.
      maxOutputTokens: Math.min(maxOutputTokensFor(liteModel, "fast"), 2500),
      onFinish: async (event) => {
        if (event.error) {
          console.error(
            JSON.stringify({
              tag: "summary-lite-stream.finish",
              paperId,
              userId: user.userId,
              hasObject: false,
              hasError: true,
              errorMessage: String(event.error).slice(0, 500),
            }),
          );
          await releaseOnFailure();
          return;
        }
        const raw = event.object as PaperSummaryLite | undefined;
        const parsed = PaperSummaryLiteSchema.safeParse(raw);
        const finalObject = parsed.success ? parsed.data : raw;
        const overview =
          typeof finalObject?.overview === "string"
            ? finalObject.overview.trim()
            : "";
        if (!overview) {
          await releaseOnFailure();
          return;
        }
        console.log(
          JSON.stringify({
            tag: "summary-lite-stream.finish",
            paperId,
            userId: user.userId,
            hasObject: true,
            hasError: false,
            usage: event.usage,
          }),
        );
        try {
          await upsertCachedAnalysis({
            userId: user.userId,
            paperId,
            key: "summary_lite",
            value: { ...finalObject, model: liteModel } as PaperSummaryLite,
          });
        } catch (err) {
          console.error("[summary-lite-stream] persist failed", err);
        }
      },
      onError: async ({ error }) => {
        console.error(
          JSON.stringify({
            tag: "summary-lite-stream.error",
            paperId,
            userId: user.userId,
            error: String(error).slice(0, 800),
          }),
        );
        await releaseOnFailure();
      },
    });
  } catch (e) {
    await releaseOnFailure();
    const message = e instanceof Error ? e.message : "Provider error";
    return jsonError(502, "provider_error", message);
  }

  return result.toTextStreamResponse({
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "no-store, no-transform",
      "X-Accel-Buffering": "no",
      "X-Know-Model": liteModel,
    },
  });
}
