from pydantic_settings import BaseSettings
from pathlib import Path


class Settings(BaseSettings):
    app_name: str = "Know"
    papers_dir: Path = Path(__file__).resolve().parent.parent.parent / "papers"
    anthropic_api_key: str = ""
    analysis_model: str = "mistral-small-latest"
    fast_model: str = "mistral-small-latest"

    # Clerk auth
    clerk_jwks_url: str = ""
    clerk_issuer: str = ""
    clerk_audience: str = ""

    # Supabase
    supabase_url: str = ""
    supabase_key: str = ""

    # Stripe
    stripe_secret_key: str = ""
    stripe_webhook_secret: str = ""
    stripe_price_scholar: str = ""
    stripe_price_researcher: str = ""

    # CORS (comma-separated production domains, never use *)
    cors_origins: str = ""

    # Internal server-to-server bearer token for the /api/internal/*
    # router. Generated by the Vercel deploy and shared with this
    # backend; required only for the migrated streaming routes that
    # run on Next.js but call back into Python for paper context,
    # usage reservation, and figure bytes. Also reused as the bearer
    # for our outbound Vercel calls (rate-check, etc.).
    internal_backend_token: str = ""

    # Optional Vercel URL the trial flow consults for KV-backed rate
    # limiting (replaces the in-process deque). When set the Python
    # trial endpoints call POST {url}/api/trial/rate-check; on any
    # transport failure they fall back to the Supabase RPC, then fail
    # closed. Leave empty to keep using Supabase RPC only.
    nextjs_ratelimit_url: str = ""

    # Set to "1" to stop running the in-process trial cleanup loop
    # because a Vercel Cron job at /api/cron/cleanup-trial owns the
    # schedule now. Defaults off so existing deploys keep the loop
    # running until the cron is verified.
    disable_internal_cron_fallback: str = ""

    # OpenAI embeddings for RAG (Track D)
    embedding_provider: str = "openai"
    embedding_model: str = "text-embedding-3-small"
    openai_api_key: str = ""

    # Mistral OCR — canonical paper markdown at upload time
    mistral_api_key: str = ""

    model_config = {"env_prefix": "KNOW_", "env_file": ".env", "extra": "ignore"}


settings = Settings()
settings.papers_dir.mkdir(parents=True, exist_ok=True)

import logging as _cfg_logging
_cfg_logger = _cfg_logging.getLogger("know.config")
if not settings.supabase_url or not settings.supabase_key:
    _cfg_logger.warning("Supabase not configured — persistence disabled, limits will fail closed")
if not settings.clerk_jwks_url:
    _cfg_logger.warning("KNOW_CLERK_JWKS_URL not set — authentication will reject all requests")
